language: java
sudo: required
dist: bionic

jdk:
  - openjdk11

addons:
  apt:
    packages:
      - ant
  sonarcloud:
    organization: "dita-ot-plugins"
    token:
      secure: "rB7cj/DUInirYU7JOlScQ4vSZBpFc+lcfdunNXtfTy6EH1ETXP8oMi2YCDIKZ1zLVx045LF7mJR6paykgGStO6RX+Z9/og7BOVyIE2sl8NOCvase48doVZ6dM7tyav/aYUAHD+AyLCIAN7Vhns+TLeJgqd/v9ExvM3K214mVg5hxTWSELcDNU4ERBXACua07evJ/VCN9tV0if11pBVa6ZvaYp8hXj/PTiax35fmttKg9TIy3PT4fCZpEKMknDFLKJ93ngms49dw3EX4ZK98g2Ehey2hQMdautcO2dYeWzTP66olIPR8BzFidIzQTt3D44erhn52n0sx5EOqmMbVH/ecZrnRz9T4iXKxCQtp1Tk6b5+uWXpx3nG6TMvPeEvl4yDYL4PCR9m19Q8xL7Rh3O88KerYSAukM94n4GcQbabEGU2qjUk8vx6VHLTwoxKfpAajFKGnx9xZe/jxiGvWg8xBAqHViOp1sfvkvene4Y0dTEu8UDLQeyUKnDB4+fB57xAr5bMQSgOqbcuWvtNMSYUfxoGg/2EYaajOsPTZvlA4VqT52wZmLqhl0hrUc7UgGIBrC+/ljZdSlx+DiEBcPg+QojPxAVpM5zLUpH0g05pf64CiYxrR+sThLUC9+H/TsnP4YDK4TZAyPCNzWBzGtKW/BrCrsaxByxAKobMkwN2Q="

before_install:
  - zip -r com.here.validate.svrl.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT/dita-ot-$DITA_OT.zip
  - unzip -q dita-ot-$DITA_OT.zip
  - chmod +x dita-ot-$DITA_OT/bin/dita

install:
  - dita-ot-$DITA_OT/bin/dita install https://github.com/jason-fox/fox.jason.unit-test/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita install https://github.com/doctales/org.doctales.xmltask/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita install com.here.validate.svrl.zip

script:
  - travis_wait 30 dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/com.here.validate.svrl -f unit-test --output . -v

jobs:
  include:
    - stage: test
      name: "Unit Tests: DITA_OT=3.4"
      env: DITA_OT=3.5

      before_script:
        - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/com.here.validate.svrl -f xsl-instrument

      after_success:
        - cp dita-ot-$DITA_OT/plugins/fox.jason.unit-test/resource/pom.xml pom.xml
        - mvn clean org.eluder.coveralls:coveralls-maven-plugin:report
        - rm -rf dita-ot-$DITA_OT
        - sonar-scanner
